[workspace]
members = [
    "kailua_env",
    "kailua_diag",
    "kailua_test",
    "kailua_syntax",
    "kailua_types",
    "kailua_check",
    "kailua_workspace",
    "kailua_langsvr",
    "kailua_langsvr_protocol",
]

[profile.release]
lto = true
debug = true # TODO

