[package]
name = "kailua_syntax"
version = "0.1.0"
authors = ["Kang Seonghoon <public+git@mearie.org>"]
build = "build.rs"

[dependencies]
lalrpop-util = "0.7.0"
custom_derive = "0.1.2"
newtype_derive = "0.1.2"

[build-dependencies]
lalrpop = "0.7.0"
