[package]
name = "kailua_syntax"
version = "0.1.0"
authors = ["Kang Seonghoon <public+git@mearie.org>"]
publish = false

[[bin]]
name = "kailua-parse"

[[test]]
name = "kailua-parse-test"
harness = false

[dependencies]
custom_derive = "0.1.2"
newtype_derive = "0.1.2"
kailua_diag = { path = "../kailua_diag" }

[dev-dependencies]
env_logger = "0.3"
regex = "0.1"
kailua_test = { path = "../kailua_test" }
