[package]
name = "kailua_diag"
version = "0.1.0"
authors = ["Kang Seonghoon <public+git@mearie.org>"]
publish = false

[dependencies]
term = "0.4.4"
unicode-width = "0.1.3"
parse-generics-shim = "0.1.0"
winapi = "0.2.7"
kernel32-sys = "0.2.2"
