[package]
name = "kailua_check"
version = "0.1.0"
authors = ["Kang Seonghoon <public+git@mearie.org>"]
publish = false

[dependencies]
log = "0.3"
env_logger = "0.3"
bitflags = "0.7"
vec_map = "0.4"
kailua_diag = { path = "../kailua_diag" }
kailua_syntax = { path = "../kailua_syntax" }
